name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Check Server Performance
        run: |
          echo "--------------------------CPU信息--------------------------"
          echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo "CPU核心数量: $(nproc)"
          echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
          echo "--------------------------内存信息--------------------------"
          echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
          echo "--------------------------硬盘信息--------------------------"
          echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

      - name: Install dependencies
        run: |
          docker rmi $(docker images -q)
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* hhvm* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* adoptopenjdk* mysql* php* mongodb* moby* snap* || true
          sudo apt -y autoremove --purge
          sudo apt update && sudo apt install repo -y
          sudo apt clean
          sudo git config --global user.name "root"
          sudo git config --global user.email "localhost"
          sudo timedatectl set-timezone Asia/Shanghai

      - name: Setup kernel source
        run: |
          repo init --repo-rev=v2.16 --depth=1 -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10-2023-01
          sed -i '/\"common\"/s/android12-5.10-2023-01/deprecated\/android12-5.10-2023-01/g' .repo/manifests/default.xml
          repo sync -c --no-tags

      - name: Setup KernelSU
        run: |
          #curl -LSs https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh | bash
          #cat KernelSU/kernel/export_symbol.txt | awk '{sub("[ \t]+","");print "  "$0}' >> common/android/abi_gki_aarch64
          timedatectl set-timezone Asia/Shanghai

      - name: Build images
        run: |
          #wget -O common/build.config.gki https://raw.githubusercontent.com/bugme2/kernel-gki-build/main/build.config.gki
          sed -i 's/ -dirty//g' common/scripts/setlocalversion
          sed -i 's/return mode == THERMAL_DEVICE_ENABLED/return mode == THERMAL_DEVICE_DISABLED/' common/drivers/thermal/thermal_core.c
          #sed -i 's/DKSU_VERSION=16/DKSU_VERSION=11628/' common/drivers/kernelsu/Makefile
          tools/bazel run --config=release --lto=thin //common:kernel_aarch64_dist -- --dist_dir=out
          echo "BUILD_TIME=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_TIME }}
          path: out/boot.img
